---
name: Publish package
  on:
    push:
      branches:
        - main
      tags:
        - v0.0.*
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    password: ${{ secrets.PYPI_API_TOKEN }}
